# -*- coding: utf-8 -*-
"""bank_loan_analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oSDtgz88-jdrI1obe-qP0C-hyXxw-TwB
"""

pip install pandas matplotlib seaborn

# ==========================================
# BANK LOAN ANALYTICS PROJECT
# ==========================================

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Create folders
os.makedirs("charts", exist_ok=True)
os.makedirs("output", exist_ok=True)

# Load Dataset
df = pd.read_csv("train.csv")

print("\n===== DATASET INFO =====\n")
print(df.info())

print("\n===== FIRST 5 ROWS =====\n")
print(df.head())

# Fill Missing Values
df["Gender"] = df["Gender"].fillna(df["Gender"].mode()[0])
df["Married"] = df["Married"].fillna(df["Married"].mode()[0])
df["Dependents"] = df["Dependents"].fillna(df["Dependents"].mode()[0])
df["Self_Employed"] = df["Self_Employed"].fillna(df["Self_Employed"].mode()[0])
df["LoanAmount"] = df["LoanAmount"].fillna(df["LoanAmount"].median())
df["Credit_History"] = df["Credit_History"].fillna(df["Credit_History"].mode()[0])

# Save Cleaned Dataset
df.to_csv("output/cleaned_loan_data.csv", index=False)

# ==========================================
# 1. LOAN APPROVAL STATUS
# ==========================================

plt.figure(figsize=(6,4))
sns.countplot(x="Loan_Status", data=df)

plt.title("Loan Approval Status")
plt.savefig("charts/loan_status.png")
plt.show()

# ==========================================
# 2. GENDER ANALYSIS
# ==========================================

plt.figure(figsize=(6,4))
sns.countplot(x="Gender", hue="Loan_Status", data=df)

plt.title("Gender vs Loan Status")
plt.savefig("charts/gender_vs_loan.png")
plt.show()

# ==========================================
# 3. EDUCATION ANALYSIS
# ==========================================

plt.figure(figsize=(6,4))
sns.countplot(x="Education", hue="Loan_Status", data=df)

plt.title("Education vs Loan Status")
plt.savefig("charts/education_vs_loan.png")
plt.show()

# ==========================================
# 4. PROPERTY AREA ANALYSIS
# ==========================================

plt.figure(figsize=(8,5))
sns.countplot(x="Property_Area", hue="Loan_Status", data=df)

plt.title("Property Area vs Loan Status")
plt.savefig("charts/property_vs_loan.png")
plt.show()

# ==========================================
# 5. CREDIT HISTORY ANALYSIS
# ==========================================

plt.figure(figsize=(6,4))
sns.countplot(x="Credit_History", hue="Loan_Status", data=df)

plt.title("Credit History Impact")
plt.savefig("charts/credit_history.png")
plt.show()

# ==========================================
# 6. APPLICANT INCOME DISTRIBUTION
# ==========================================

plt.figure(figsize=(8,5))
sns.histplot(df["ApplicantIncome"], bins=30)

plt.title("Applicant Income Distribution")
plt.savefig("charts/income_distribution.png")
plt.show()

# ==========================================
# INSIGHTS
# ==========================================

print("\n===== KEY INSIGHTS =====\n")

print("1. Analyze loan approval trends.")
print("2. Study effect of credit history.")
print("3. Compare education levels.")
print("4. Understand applicant income patterns.")
print("5. Analyze property area influence.")

print("\nPROJECT COMPLETED SUCCESSFULLY!")